### ISSUE TITLE
Data pre-processing code

### ISSUE THREAD

**Issue by nicolasugrinovic** [ZhengyiLuo/EmbodiedPose#6]
Hi,  I used the script `data_process/process_humor_split.py` to generate the same data as the one provided in `sample_data/thirdeye_anns_prox_overlap_no_clip.pkl` for PROX "N0Sofa_00145_01" sequence. I have the same data fields as the file provided in the repo, however, when I run the method I don't have the same results. When using `sample_data/thirdeye_anns_prox_overlap_no_clip.pkl` data, it works ok but when I use the data generated by `process_humor_split.py` the result is not good. 

Can you provide the code used for generating `sample_data/thirdeye_anns_prox_overlap_no_clip.pkl`?

Thanks. Best,

**Comment by ZhengyiLuo** [comment]
Could you elaborate on "don't have the same results"? Which part is not the same? 

We only uses the first frame information from HuMoR as initialization (which can be replaced with any monocular pose estimation methods, I am using HyerIK for the in-the-wild demo I am building). Also, as mentioned in the paper, we used [DEKR](https://github.com/HRNet/DEKR) as our 2D pose estimation instead of OpenPose. In reality, we only need the first frame of HuMoR result (pose_aa and trans) plus the joints2d and camera fields in the pkl file. I attached [one such file](https://drive.google.com/file/d/15Z96jynyUZwrd5wxjA0uUM-Ru-X1F4-3/view?usp=sharing) with all the other values other than the first frame zeroed out as an example. 

As for `thirdeye_anns_prox_overlap_no_clip.pkl`, it is indeed generated from HuMoR result using the included script, but we run HuMoR with customized config file to enable smooth overlapping. Unfortunately this process is not stable and optimization could fail, creating crazy human movement. We manually identify those frames and rerun HuMoR in those cases. It is quite a painful process. The code for that can be found my fork here [HuMoR](https://github.com/ZhengyiLuo/humor).

**Comment by ZhengyiLuo** [comment]
Also the reason we did all the overlapping processing HuMoR was we were thinking about training with the HuMoR result on Prox. Once we realize how unstable it is and how the model doesn't really need to be trained on Prox to (almost) work, we went with the current formulation.

**Comment by ZhengyiLuo** [comment]
Another note is the keypoint ordering needs to be carefully processed...
