### ISSUE TITLE
error load xml

### ISSUE THREAD

**Issue by luoww1992** [ZhengyiLuo/EmbodiedPose#7]
error:
    Failed to load XML from file: C:\Users\admin\AppData\Local\Temp\tmp5h7qhqh9.xml. mj_loadXML error: b"XML Error: Schema violation: unrecognized attribute: 'name'\n\nElement 'exclude', line 264, column 5\n"

i use dance.mp4 as the wild video to run it. it run step1 and step2  is good, 
but when run step3:  python scripts/eval_scene.py --cfg tcn_voxel_4_5 --epoch -1 --data sample_data/wild_processed.pkl
show me error,  these are nothing changed.

**Comment by ZhengyiLuo** [comment]
Could you run `python uhc/smpllib/smpl_robot.py` from the UniversalHumanoidController repo? It looks like it's having problem loading the xml. Follow the instruction for UHC and make sure it runs since this repo depends on it. 

I have not tested the code on windows though so I do not really know what to expect.
